### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by birkir** [ueno-llc/ueno-cra-starter#1]
- [ ] Hot reload mobx stores support

Done

 - [x] Stylelint
 - [x] Static builds
 - [x] Config/values alternative
 - [x] Use `const isDev = process.env.NODE_ENV === 'development';` in lib/server
 - [x] Use `webpack-node-externals` for server.
 - [x] Add `aggregateTimeout` to watchOptions for server (better client performance).
 - [x] Put `stats` to minimal for server to reduce mini-css logs
 - [x] Heroku pipeline support
 - [x] Clean up server webpack output in CLI (looking at you mini-css-plugin)
 - [x] Make sure service worker works
 - [x] Polyfills and browser support
 - [x] GSAP works
 - [x] import resolver ('components/foo' vs '../components/foo')
 - [x] DevTools (Grid)

**Comment by jeremybarbet** [comment]
What about exposing the `getLocalApiUrl ` from https://github.com/ueno-llc/starter-kit-universally/blob/development/config/utils/publicPath.js#L31 since we use api in most of the case

**Comment by jeremybarbet** [comment]
I just closed the other issue and group others ideas here

- [ ] Use the app-name to populate the different .json files and meta tags.
- [ ] Create a gsapdevtool component to wrap any component with timelines and be able to debug them or make it works globally on every routes
- [ ] Create a private package for the devtools to be able to use them on the other starter kit repo
